### PR TITLE
Trym dev

### PR DESCRIPTION
**Pull request by trykvi**
BAiO implementation.

4 agents added in chat/baio_container/baio_agents.json

Streaming response now includes the function calls the model makes along with the results of those function calls.

Created new endpoint for getting csv files, along with view, model and serializer. Also changed the getConversation endpoint to include references to the csvfiles in each message under 'csv_files' in the response body.

Still need to create some tests and documentation, and there are still several issues with baio itself. But the baio integration with the backend is practically complete.

### CODE REVIEW

**Comment by trykvi** [comment]
Massive pull request since baio was added directly to the repository

**Comment by stianbekk** [comment]
Very nice

**Comment by stianbekk** [comment]
Very nice

**Review by stianbekk — APPROVED** [review]
Very nice!

**Pull request merged**
